server:
    host: localhost
    port: 8000
    public: ../public
    mongodb: mongodb://localhost:27017/RiffTeam
    paginate:
        default: 10
        max: 50

log:
    name: RiffTeam
    level: trace
    streams:
        -
            output: file
            level: info
            logDir: "./logs"
            type: rotating-file
            period: 1d
            count: 10
        -
            output: stderr
